export const GET_ALL_POKEMONS_START = "GET_ALL_POKEMONS_START";
export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";
export const GET_ALL_POKEMONS_FAIL = "GET_ALL_POKEMONS_FAIL";

export const GET_POKEMON_BY_ID_START = "GET_POKEMON_BY_ID_START";
export const GET_POKEMON_BY_ID_SUCCESS = "GET_POKEMON_BY_ID_SUCCESS";
export const GET_POKEMON_BY_ID_FAIL = "GET_POKEMON_BY_ID_FAIL";
